FROM golang:1.15.7-buster

ENV GO111MODULE=on

ENV PROJECT_NAME ${PROJECT_NAME}
ENV APP_NAME ${APP_NAME}
ENV DB_HOST ${DB_HOST}
ENV DB_USER ${DB_USER}
ENV DB_PASS ${DB_PASS}
ENV DB_NAME ${DB_NAME}

RUN mkdir -p /app
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/api
EXPOSE 8000
CMD ["/app/api"]
