version: '3.1'
services:
  testnats:
    image: nats:latest
    entrypoint: /nats-server -js
    ports:
      - 4222:4222
  testpsql:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${DB_PASS}
      PGPASSWORD: ${DB_PASS}
      PGDATA: /data
    volumes:
      - /tmp/data/psql:/data
    command: postgres -N 1000 -c fsync=off -c full_page_writes=off
    ports:
      - 5432:5432
  testelastic1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
    environment:
      - node.name=testelastic1
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=testelastic2
      - cluster.initial_master_nodes=testelastic1,testelastic2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /tmp/data/elastic1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  testelastic2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.0
    environment:
      - node.name=testelastic2
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=testelastic1
      - cluster.initial_master_nodes=testelastic1,testelastic2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /tmp/data/elastic2:/usr/share/elasticsearch/data
