version: '3.1'
services:
  testnats:
    image: nats:latest
    entrypoint: /nats-server -js
    ports:
      - 4222:4222
  testpsql:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${DB_PASS}
      PGPASSWORD: ${DB_PASS}
      PGDATA: /data
    volumes:
      - /tmp/data/psql:/data
    command: postgres -N 1000 -c fsync=off -c full_page_writes=off
    ports:
      - 5432:5432

  testes01:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.20
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  testes02:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.20
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=testes01"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  testkib01:
    image: docker.elastic.co/kibana/kibana:6.8.20
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://testes01:9200
      ELASTICSEARCH_HOSTS: '["http://testes01:9200","http://testes02:9200"]'
