version: '3.1'
services:
  testnats:
    image: nats:latest
    entrypoint: /nats-server -js
    ports:
      - 4222:4222
  testservice:
    image: herpiko/dddcqrs-service
    environment:
      NATS_URL: 'nats://testnats:4222'
      ELASTIC_ADDRESS: 'testes01:9200'
      GRPC_ADDRESS: 'testservice:4040'
      DB_HOST: 'testpsql'
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports:
      - 4040:4040
  testhttp:
    image: herpiko/dddcqrs-http
    environment:
      NATS_URL: 'nats://testnats:4222'
      ELASTIC_ADDRESS: 'testes01:9200'
      GRPC_ADDRESS: 'testservice:4040'
      DB_HOST: 'testpsql'
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports:
      - 8000:8000
  testcommand:
    image: herpiko/dddcqrs-command
    environment:
      NATS_URL: 'nats://testnats:4222'
      ELASTIC_ADDRESS: 'testes01:9200'
      GRPC_ADDRESS: 'testservice:4040'
      DB_HOST: 'testpsql'
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
  testquery:
    image: herpiko/dddcqrs-query
    environment:
      NATS_URL: 'nats://testnats:4222'
      ELASTIC_ADDRESS: 'testes01:9200'
      GRPC_ADDRESS: 'testservice:4040'
      DB_HOST: 'testpsql'
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
  testeventstore:
    image: herpiko/dddcqrs-eventstore
    environment:
      NATS_URL: 'nats://testnats:4222'
      ELASTIC_ADDRESS: 'testes01:9200'
      GRPC_ADDRESS: 'testservice:4040'
      DB_HOST: 'testpsql'
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
  testpsql:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${DB_PASS}
      PGPASSWORD: ${DB_PASS}
      PGDATA: /data
    volumes:
      - /tmp/data/psql:/data
    command: postgres -N 1000 -c fsync=off -c full_page_writes=off
    ports:
      - 5432:5432

  testes01:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.20
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  testes02:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.20
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=testes01"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  testkib:
    image: docker.elastic.co/kibana/kibana:6.8.20
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://testes01:9200
      ELASTICSEARCH_HOSTS: '["http://testes01:9200","http://testes02:9200"]'
