port: 4443
services:
  - name: proxy
    hostname: "localhost"
    routes:
    - prefix: /api
      name: api
      upstream: 172.17.0.1
      port: 8000
    - prefix: /
      name: frontend
      upstream: 172.17.0.1
      port: 3000
